language: go
go:
  - 1.3
env: "PATH=/home/travis/gopath/bin:$PATH"
install:
  - go get github.com/mitchellh/gox
  - go get -d -v ./..."
script:
  - go test ./...
  - gox -osarch="darwin/amd64" -output="recodesign"
deploy:
  provider: releases
  api_key:
    secure: WwtPTfiJ+5ZTnGFozPfwRiom9wyQgJS7o3oP5/nwa6OpPU+qWhVQKfwKhFW0X0rquC9F3qRqwuS0yeWGnVW19APVmkFdI0c2GX/I4RTZXg4qb66ZNRk5+mLiGO1OPSPuVpBy4402KBiU6hoOKmRmwXqC742V77XGndzS037Bp5E=
  file: recodesign
  skip_cleanup: true
  on:
    repo: seiji/recodesign
    all_branches: true
    tags: true
    condition: "$TRAVIS_GO_VERSION = go1.3"
